AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trailcams-email-handler

  SAM Template for Email Handler lambda function

Globals:
  Function:
    Timeout: 3

Resources:
  EmailHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: email-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

Outputs:
  EmailHandlerFunction:
    Description: "Email Handler Lambda Function ARN"
    Value: !GetAtt EmailHandlerFunction.Arn
  EmailHandlerRole:
    Description: "Implicit IAM Role created for Email Handler function"
    Value: !GetAtt EmailHandlerFunction.Arn
